# build stage
FROM node:lts-bullseye 
# Set environment variables for non-interactive npm installs
ENV NPM_CONFIG_LOGLEVEL warn
ENV CI true

# WORKDIR /app
# COPY package.json pnpm-lock.yaml ./
# RUN npm install -g pnpm && pnpm i --frozen-lockfile
# COPY . .
# RUN pnpm build

RUN apt-get update && apt-get install vim  sudo -y  && npm install -g pnpm

ARG UID
ARG GID

RUN groupadd --gid $GID lighthouse && \
    useradd --uid $UID --gid $GID --create-home lighthouse && \
    echo 'lighthouse ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER lighthouse
WORKDIR /home/lighthouse

